### PR TITLE
[Issue 491][rpc_client]fix: timeout guarantee for RequestOnCnx

### LINKED ISSUE #491: Producer block may block forever
#### Expected behavior

If producer.Close are called,it will close within configured OperationTimeout

#### Actual behavior

producer.Close may block forever and won't time out after configured OperationTimeout

#### Steps to reproduce

Just run the perf program for a while and send SIGINT or ctrl+c to it. This situation may be triggered.

This is because the callback of [producer.SendAsyc](https://github.com/apache/pulsar-client-go/blob/master/perf/perf-producer.go#L132) contains a send behavior on a channel which under the same scope with [stopCh](https://github.com/apache/pulsar-client-go/blob/master/perf/perf-producer.go#L145-L162). When we trigger producer.Close, if `case <-stop:` happens before `case latency := <-ch:`, it will block forever because it may be block at [here](https://github.com/apache/pulsar-client-go/blob/master/pulsar/producer_partition.go#L700) and [RequestOnCnx](https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/rpc_client.go#L146-L165) has no time out guarantee.

#### System configuration
**Pulsar version**: any

### PR DESCRIPTION
**Pull request by jonyhy96**
Fixes #491 

### Motivation

see #491

### Modifications

add timeout guarantee to RequestOnCnx

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - **The public API: (yes)**
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: pulsar/internal/rpc_client.go [hunk 1]
```diff
@@ -139,29 +144,30 @@ func (c *rpcClient) Request(logicalAddr *url.URL, physicalAddr *url.URL, request
...
 func (c *rpcClient) RequestOnCnx(cnx Connection, requestID uint64, cmdType pb.BaseCommand_Type,
 	message proto.Message) (*RPCResult, error) {
 	c.metrics.RPCRequestCount.Inc()
-	wg := sync.WaitGroup{}
-	wg.Add(1)
 
-	rpcResult := &RPCResult{
-		Cnx: cnx,
-	}
+	ch := make(chan result, 1)
```
Comment (wolfstudy) [inline pulsar/internal/rpc_client.go:155]: Can we consider adjusting the size of the channel buffer appropriately? It looks like 10 is a good choice?

**Review by wolfstudy — COMMENTED** [review]
The change LGTM +1, just a little comments, please check

File: pulsar/internal/rpc_client.go (hunk 1 above)
Comment (jonyhy96) [reply pulsar/internal/rpc_client.go:155]: 0 maybe enough for this because there will be only one result sends to `ch` . Set it to 1  to prevent block happens on the sender side.

**Comment by omnilight** [comment]
@wolfstudy @jonyhy96 Hi. Could we proceed with this PR? Lack of the timeout on connection is a problem causing locking producer, would be great if we can release this fix

**Review by freeznet — APPROVED** [review]
LGTM

**Review by wolfstudy — APPROVED** [review]
Great job! LGTM +1
