### PR TITLE
Fix: Potential data race

### LINKED ISSUE #1337: [Bug][Producer/Connection] Potential data race
#### Expected behavior

After `pendingItem.done()` is called, `pendingItem.buffer`  that are holding in `connection.writeRequestsCh` should not be written to network by `conneciton.internalWriteData()/conneciton.cnx.Write()`.

#### Actual behavior

1. When we send message, we pass `pendingItem.buffer` to `connection.writeRequestsCh`;
2. `connection.writeRequestsCh` is a buffered channel(`writeRequestsCh:  make(chan Buffer, 256)`), which means the buffer will be written to network later/asnyc;
3. If `pendingItem` timeout happen before `pendingItem.buffer` being sent to network, `pendingItem.buffer` will be put back to the pool and realloced, but `connection.writeRequestsCh` still hold the reference of the OLD buffer;
4. Now, if we run to `conneciton.internalWriteData()/conneciton.cnx.Write()`, data race will happen, we intent to send the OLD `pendingItem.buffer`, but the buffer holds the data of a NEW `pendingItem`；
5. Because timeout is longer than sending, it hasn't happened in reality, but it is theoretically possible.

#### Steps to reproduce

Code review:

```go
// writeData will pass `pendingItem.buffer` to `connection.writeRequestsCh`
func (p *partitionProducer) writeData(buffer internal.Buffer, sequenceID uint64, callbacks []interface{}) {
	select {
	case <-p.ctx.Done():
		for _, cb := range callbacks {
			if sr, ok := cb.(*sendRequest); ok {
				sr.done(nil, ErrProducerClosed)
			}
		}
		return
	default:
		now := time.Now()
		p.pendingQueue.Put(&pendingItem{
			createdAt:    now,
			sentAt:       now,
			buffer:       buffer,
			sequenceID:   sequenceID,
			sendRequests: callbacks,
		})
		p._getConn().WriteData(buffer)
	}
}

// `connection.writeRequestsCh` is a buffer channel
func newConnection(opts connectionOptions) *connection {
	cnx := &connection{
		
		// This channel is used to pass data from producers to the connection
		// go routine. It can become contended or blocking if we have multiple
		// partition produces writing on a single connection. In general it's
		// good to keep this above the number of partition producers assigned
		// to a single connection.
		writeRequestsCh:  make(chan Buffer, 256),
		
	}
	
	return cnx
}

// `pendingItem.buffer` is held in `connection.writeRequestsCh` and will be sent in another goroutine
func (c *connection) WriteData(data Buffer) {
	select {
	case c.writeRequestsCh <- data:
		// Channel is not full
		return

	default:
		// Channel full, fallback to probe if connection is closed
	}

	for {
		select {
		case c.writeRequestsCh <- data:
			// Successfully wrote on the channel
			return

		case <-time.After(100 * time.Millisecond):
			// The channel is either:
			// 1. blocked, in which case we need to wait until we have space
			// 2. the connection is already closed, then we need to bail out
			c.log.Debug("Couldn't write on connection channel immediately")

			if c.getState() != connectionReady {
				c.log.Debug("Connection was already closed")
				return
			}
		}
	}

}

// `pendingItem.buffer` will be written to network by c.internalWriteData(data)
func (c *connection) run() {
	pingSendTicker := time.NewTicker(c.keepAliveInterval)
	pingCheckTicker := time.NewTicker(c.keepAliveInterval)

	defer func() {
		// stop tickers
		pingSendTicker.Stop()
		pingCheckTicker.Stop()

		// all the accesses to the pendingReqs should be happened in this run loop thread,
		// including the final cleanup, to avoid the issue
		// https://github.com/apache/pulsar-client-go/issues/239
		c.failPendingRequests(errConnectionClosed)
		c.Close()
	}()

	// All reads come from the reader goroutine
	go c.reader.readFromConnection()
	go c.runPingCheck(pingCheckTicker)

	c.log.Debugf("Connection run starting with request capacity=%d queued=%d",
		cap(c.incomingRequestsCh), len(c.incomingRequestsCh))

	for {
		select {
		case <-c.closeCh:
			c.failLeftRequestsWhenClose()
			return
		case req := <-c.incomingRequestsCh:
			if req == nil {
				return // TODO: this never gonna be happen
			}
			c.internalSendRequest(req)
		case cmd := <-c.incomingCmdCh:
			c.internalReceivedCommand(cmd.cmd, cmd.headersAndPayload)
		case data := <-c.writeRequestsCh:
			if data == nil {
				return
			}
			c.internalWriteData(data)

		case <-pingSendTicker.C:
			c.sendPing()
		}
	}
}


// when pendingItem is done, its buffer will be put back to the pool and realloced later
func (i *pendingItem) done(err error) {
	if i.isDone {
		return
	}
	i.isDone = true
	buffersPool.Put(i.buffer)
	if i.flushCallback != nil {
		i.flushCallback(err)
	}
}

// when `pendingItem.done()` is called before `c.internalWriteData(data)`, data race will happen
```

#### System configuration
**Pulsar version**: x.y

### PR DESCRIPTION
**Pull request by gunli**
Fixes #1337

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #1337

### Motivation

Fix potential data race

### Modifications

1. Add a context and a cancel func to pendingItem;
2. In pendingItem.done(), cancel the context;
3. If context is done, stop writing.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

No

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by gunli** [comment]
This PR should be merged after #1333 and #1336 , may be rebase is required.
@shibd @RobertIndie @nodece @BewareMyPower @crossoverJie

File: pulsar/internal/connection.go [hunk 1]
```diff
@@ -501,11 +511,25 @@ func (c *connection) WriteData(data Buffer) {
...
-		c.Close()
+	if ctx == nil {
+		if _, err := c.cnx.Write(data.ReadableSlice()); err != nil {
+			c.log.WithError(err).Warn("Failed to write on connection")
+			c.Close()
+		}
+
+		return
+	}
+
```
Comment (nodece) [inline pulsar/internal/connection.go:524]:
```suggestion
```
Unnecessary.

**Review by nodece — APPROVED** [review]
LGTM

File: pulsar/internal/connection.go (hunk 1 above)
Comment (gunli) [reply pulsar/internal/connection.go]: upadted

File: pulsar/internal/connection.go [hunk 2]
```diff
@@ -530,7 +554,7 @@ func (c *connection) writeCommand(cmd *pb.BaseCommand) {
 	}
 
 	c.writeBuffer.WrittenBytes(cmdSize)
-	c.internalWriteData(c.writeBuffer)
+	c.internalWriteData(nil, c.writeBuffer)
```
[the remark this answers is not in the document]
Comment (gunli) [reply pulsar/internal/connection.go]: upadted

**Review by shibd — DISMISSED** [review]
Same request change for this:

https://github.com/apache/pulsar-client-go/pull/1336#pullrequestreview-2644474365

File: pulsar/internal/connection.go [hunk 3]
```diff
@@ -501,11 +511,20 @@ func (c *connection) WriteData(data Buffer) {
...
 }
 
-func (c *connection) internalWriteData(data Buffer) {
+func (c *connection) internalWriteData(ctx context.Context, data Buffer) {
 	c.log.Debug("Write data: ", data.ReadableBytes())
-	if _, err := c.cnx.Write(data.ReadableSlice()); err != nil {
-		c.log.WithError(err).Warn("Failed to write on connection")
-		c.Close()
+	if ctx == nil {
+		return
```
[the remark this answers is not in the document]
Comment (gunli) [reply pulsar/internal/connection.go:517]: if I don't add this check, integration testing will failed as code coverage test fail.

File: pulsar/producer_partition.go [hunk 4]
```diff
@@ -846,6 +848,21 @@ type pendingItem struct {
 	flushCallback func(err error)
 }
 
+func (i *pendingItem) done(err error) {
```
Comment (BewareMyPower) [inline pulsar/producer_partition.go:851]: Could you avoid changing the method's position? I see you deleted the original `done` method below and added it here.

File: pulsar/internal/connection.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (nodece) [reply pulsar/internal/connection.go:517]: Please check https://github.com/apache/pulsar-client-go/actions/runs/13538441376/job/37836739015

```
2025-02-26T08:20:54.6856030Z     producer_test.go:475: 
2025-02-26T08:20:54.6856682Z         	Error Trace:	/pulsar/pulsar-client-go/pulsar/producer_test.go:475
2025-02-26T08:20:54.6857513Z         	Error:      	Expected nil, but got: &errors.errorString{s:"request timed out"}
2025-02-26T08:20:54.6858292Z         	Test:       	TestFlushInPartitionedProducer
2025-02-26T08:20:54.6858745Z --- FAIL: TestFlushInPartitionedProducer (30.02s)
2025-02-26T08:20:54.6859183Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2025-02-26T08:20:54.6859909Z 	panic: runtime error: invalid memory address or nil pointer dereference
2025-02-26T08:20:54.6860253Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c4163]
2025-02-26T08:20:54.6860265Z 
2025-02-26T08:20:54.6860426Z goroutine 14599 [running]:
2025-02-26T08:20:54.6860710Z testing.tRunner.func1.2({0x1505d80, 0x1ef9000})
2025-02-26T08:20:54.6860964Z 	/pulsar/go/src/testing/testing.go:1632 +0x3fc
2025-02-26T08:20:54.6861127Z testing.tRunner.func1()
2025-02-26T08:20:54.6861355Z 	/pulsar/go/src/testing/testing.go:1635 +0x6b6
2025-02-26T08:20:54.6861512Z panic({0x1505d80?, 0x1ef9000?})
2025-02-26T08:20:54.6861720Z 	/pulsar/go/src/runtime/panic.go:785 +0x132
2025-02-26T08:20:54.6862233Z github.com/apache/pulsar-client-go/pulsar.TestFlushInPartitionedProducer(0xc000374000)
2025-02-26T08:20:54.6862565Z 	/pulsar/pulsar-client-go/pulsar/producer_test.go:476 +0x343
2025-02-26T08:20:54.6862751Z testing.tRunner(0xc000374000, 0x16a9940)
2025-02-26T08:20:54.6862985Z 	/pulsar/go/src/testing/testing.go:1690 +0x227
2025-02-26T08:20:54.6863352Z created by testing.(*T).Run in goroutine 1
2025-02-26T08:20:54.6863588Z 	/pulsar/go/src/testing/testing.go:1743 +0x826
2025-02-26T08:20:54.6863859Z FAIL	github.com/apache/pulsar-client-go/pulsar	285.026s
```

Please remove this check.

**Review by nodece — CHANGES_REQUESTED** [review]
You should not check the `cnx` is nil, this is incorrect, I think the previous commit is correct, I know the CI failed.

Please check https://github.com/apache/pulsar-client-go/actions/runs/13538441376/job/37836739015

```
2025-02-26T08:20:54.6856030Z     producer_test.go:475: 
2025-02-26T08:20:54.6856682Z         	Error Trace:	/pulsar/pulsar-client-go/pulsar/producer_test.go:475
2025-02-26T08:20:54.6857513Z         	Error:      	Expected nil, but got: &errors.errorString{s:"request timed out"}
2025-02-26T08:20:54.6858292Z         	Test:       	TestFlushInPartitionedProducer
2025-02-26T08:20:54.6858745Z --- FAIL: TestFlushInPartitionedProducer (30.02s)
2025-02-26T08:20:54.6859183Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2025-02-26T08:20:54.6859909Z 	panic: runtime error: invalid memory address or nil pointer dereference
2025-02-26T08:20:54.6860253Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c4163]
2025-02-26T08:20:54.6860265Z 
2025-02-26T08:20:54.6860426Z goroutine 14599 [running]:
2025-02-26T08:20:54.6860710Z testing.tRunner.func1.2({0x1505d80, 0x1ef9000})
2025-02-26T08:20:54.6860964Z 	/pulsar/go/src/testing/testing.go:1632 +0x3fc
2025-02-26T08:20:54.6861127Z testing.tRunner.func1()
2025-02-26T08:20:54.6861355Z 	/pulsar/go/src/testing/testing.go:1635 +0x6b6
2025-02-26T08:20:54.6861512Z panic({0x1505d80?, 0x1ef9000?})
2025-02-26T08:20:54.6861720Z 	/pulsar/go/src/runtime/panic.go:785 +0x132
2025-02-26T08:20:54.6862233Z github.com/apache/pulsar-client-go/pulsar.TestFlushInPartitionedProducer(0xc000374000)
2025-02-26T08:20:54.6862565Z 	/pulsar/pulsar-client-go/pulsar/producer_test.go:476 +0x343
2025-02-26T08:20:54.6862751Z testing.tRunner(0xc000374000, 0x16a9940)
2025-02-26T08:20:54.6862985Z 	/pulsar/go/src/testing/testing.go:1690 +0x227
2025-02-26T08:20:54.6863352Z created by testing.(*T).Run in goroutine 1
2025-02-26T08:20:54.6863588Z 	/pulsar/go/src/testing/testing.go:1743 +0x826
2025-02-26T08:20:54.6863859Z FAIL	github.com/apache/pulsar-client-go/pulsar	285.026s
```

Your changes break this test, please fix test.

**Comment by gunli** [comment]
> Your changes break this test, please remove the `ctx` check, and then fix test.


It pass on my host.

File: pulsar/producer_partition.go (hunk 4 above)
Comment (BewareMyPower) [reply pulsar/producer_partition.go:851]: > the methods of a struct is better to be close together with its defintion,

It depends. However, moving the method's position breaks the git change log and makes code harder to review. It should really be avoided without strong reason. For example, your change here only adds 3 lines, but from the diff of this PR, you deleted 11 lines and added 14 lines.

Imagine what if I only want to add 1 line to a method, but I actually removed 100 lines and added 101 lines where 100 lines are duplicated.

> even if the best IDE goland can't jump to the methods' definitions.

I tried moving `done` back to the original position (before `_setConn`). Then I searched all references and jumped from one reference to the implementation, the LSP worked well.

If the so-called "best" IDE is so poor, I suggest switching to [vim-go](https://github.com/fatih/vim-go) for development.

https://github.com/user-attachments/assets/96cefff5-0632-48d6-85be-83e5d28e3d80

**Comment by nodece** [comment]
@gunli Please revert to https://github.com/apache/pulsar-client-go/pull/1338/commits/bc2622379f77742ad7ba16bbd333330b9273eb5f.

It seems a network issue, the ci has been re-run to research the root cause.

**Comment by gunli** [comment]
> @gunli Please revert to [bc26223](https://github.com/apache/pulsar-client-go/commit/bc2622379f77742ad7ba16bbd333330b9273eb5f).
> 
> It seems a network issue, the ci has been re-run to research the root cause.

image

All tests pass on my host, may be we should set some timeout config in the test.

File: pulsar/producer_partition.go (hunk 4 above)
Comment (gunli) [reply pulsar/producer_partition.go:851]: image
It can jump from here.

Comment (BewareMyPower) [reply pulsar/producer_partition.go:851]: Let's not discuss about the IDE issues. Some questions:
1. Is there any CI that prevents a new method inserted between the `pendingItem` struct and its `done` method?
2. If not and a new struct is inserted between these, you're going to push another PR to make `done` close to `pendingItem` so that your IDE could be satisfied?

Please don't pollute the commit diff by moving a whole method to another position.

File: pulsar/internal/connection.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (nodece) [reply pulsar/internal/connection.go:522]: @gunli

File: pulsar/producer_partition.go (hunk 4 above)
Comment (nodece) [reply pulsar/producer_partition.go:851]: > Please don't pollute the commit diff by moving a whole method to another position.

+1

File: pulsar/internal/connection.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (gunli) [reply pulsar/internal/connection.go]: done

File: pulsar/producer_partition.go (hunk 4 above)
Comment (gunli) [reply pulsar/producer_partition.go]: OK, I have reverted it.

**Review by nodece — APPROVED** [review]

**Comment by gunli** [comment]
mark is as draft until #1336 is merged

**Review by nodece — APPROVED** [review]
