### PR TITLE
[Issue 306] Change connection failed warn log to error and print error message

### LINKED ISSUE #306: Should clear Error/Warn log
#### Expected behavior

Got detail error message when connection failed.

#### Actual behavior

Just got `WARN[0000] Failed to perform initial handshake - Expecting 'Connected' cmd, got 'ERROR'   local_addr="192.168.1.11:49262" remote_addr="pulsar://192.168.1.11:6560"`

#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

#### Other

connection.go#doHandshake
```
	if cmd.Connected == nil {
		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s' ",
			cmd.Type)
		return false
	}
```

Can  we use `cmd.GetError().GetMessage()`     instead of  `cmd.Type` ? just like :  

```
	if cmd.Connected == nil {
		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s' ",
			cmd.GetError().GetMessage())
		return false
	}
```

 and it can let me got `WARN[0000] Failed to perform initial handshake - Expecting 'Connected' cmd, got 'Unable to authenticate'  local_addr="192.168.1.11:50334" remote_addr="pulsar://192.168.1.11:6560"`. Maybe it should be `Error`   instead of  `Warn`.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Fixes #306 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

Print a clean log when the connection failed.

### CODE REVIEW

File: pulsar/internal/connection.go [hunk 1]
```diff
@@ -287,8 +287,8 @@ func (c *connection) doHandshake() bool {
 	c.cnx.SetDeadline(time.Time{})
 
 	if cmd.Connected == nil {
-		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s'",
-			cmd.Type)
+		c.log.Errorf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s'",
```
Comment (wolfstudy) [inline pulsar/internal/connection.go:290]: About log level I think `Warnf` is more appropriate, it has not reached the Error level

Comment (liangyuanpeng) [reply pulsar/internal/connection.go:290]: How do we define the error level ? The client can't not working when this error happend and why just got warn log?

Comment (merlimat) [reply pulsar/internal/connection.go:290]: The message itself need to be changed though. It was basically a "debug" message. In this case, the user doesn't know what's a `Connected cmd`.

File: pulsar/internal/connection.go [hunk 2]
```diff
@@ -288,7 +288,7 @@ func (c *connection) doHandshake() bool {
 
 	if cmd.Connected == nil {
 		c.log.Warnf("Failed to perform initial handshake - Expecting 'Connected' cmd, got '%s'",
-			cmd.Type)
+			cmd.Error.GetMessage())
```
Comment (merlimat) [inline pulsar/internal/connection.go:291]: Please change the original message since with this change it wouldn't make sense anymore:

```
c.log.Warnf("Failed to establish connection with broker: '%s'",
```
