### PR TITLE
[Flaky Test]: Fix flaky test TestMaxPendingChunkMessages()

### LINKED ISSUE #983: Flaky Test: TestMaxPendingChunkMessages
Example failure: https://github.com/apache/pulsar-client-go/actions/runs/4352893665/jobs/7606246572

Log:
```
2023-03-07T10:15:51.9874801Z === RUN   TestMaxPendingChunkMessages
2023-03-07T10:15:51.9875376Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9875933Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40150" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9876586Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40150" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9877268Z time="2023-03-07T10:12:36Z" level=info msg="Connected producer" cnx="127.0.0.1:40150 -> 127.0.0.1:6650" epoch=0 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9878089Z time="2023-03-07T10:12:36Z" level=info msg="Created producer" cnx="127.0.0.1:40150 -> 127.0.0.1:6650" producerID=1 producer_name=standalone-0-422 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9878584Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9879427Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40160" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9879941Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40160" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9880694Z time="2023-03-07T10:12:36Z" level=info msg="Connected producer" cnx="127.0.0.1:40160 -> 127.0.0.1:6650" epoch=0 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9881600Z time="2023-03-07T10:12:36Z" level=info msg="Created producer" cnx="127.0.0.1:40160 -> 127.0.0.1:6650" producerID=1 producer_name=standalone-0-424 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9882066Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9882598Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40164" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9883107Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40164" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9883696Z time="2023-03-07T10:12:36Z" level=info msg="Connected producer" cnx="127.0.0.1:40164 -> 127.0.0.1:6650" epoch=0 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9884377Z time="2023-03-07T10:12:36Z" level=info msg="Created producer" cnx="127.0.0.1:40164 -> 127.0.0.1:6650" producerID=1 producer_name=standalone-0-425 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9885174Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9885723Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40170" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9886251Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40170" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9886855Z time="2023-03-07T10:12:36Z" level=info msg="Connected producer" cnx="127.0.0.1:40170 -> 127.0.0.1:6650" epoch=0 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9887558Z time="2023-03-07T10:12:36Z" level=info msg="Created producer" cnx="127.0.0.1:40170 -> 127.0.0.1:6650" producerID=1 producer_name=standalone-0-426 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9888033Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9888698Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40182" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9889313Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40182" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9889864Z time="2023-03-07T10:12:36Z" level=info msg="Connected producer" cnx="127.0.0.1:40182 -> 127.0.0.1:6650" epoch=0 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9890492Z time="2023-03-07T10:12:36Z" level=info msg="Created producer" cnx="127.0.0.1:40182 -> 127.0.0.1:6650" producerID=1 producer_name=standalone-0-427 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9891034Z time="2023-03-07T10:12:36Z" level=info msg="Connecting to broker" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9891576Z time="2023-03-07T10:12:36Z" level=info msg="TCP connection established" local_addr="127.0.0.1:40192" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9892248Z time="2023-03-07T10:12:36Z" level=info msg="Connection is ready" local_addr="127.0.0.1:40192" remote_addr="pulsar://localhost:6650"
2023-03-07T10:15:51.9893004Z time="2023-03-07T10:12:36Z" level=info msg="Connected consumer" consumerID=1 name=spsfq subscription=chunk-subscriber topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9893763Z time="2023-03-07T10:12:36Z" level=info msg="Created consumer" consumerID=1 name=spsfq subscription=chunk-subscriber topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9894060Z     message_chunking_test.go:236: 
2023-03-07T10:15:51.9895061Z         	Error Trace:	/pulsar/pulsar-client-go/pulsar/message_chunking_test.go:236
2023-03-07T10:15:51.9895399Z         	Error:      	Should not be: 200
2023-03-07T10:15:51.9895709Z         	Test:       	TestMaxPendingChunkMessages
2023-03-07T10:15:51.9896377Z time="2023-03-07T10:12:37Z" level=info msg="Closing consumer=1" consumerID=1 name=spsfq subscription=chunk-subscriber topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9897045Z time="2023-03-07T10:12:37Z" level=info msg="Closed consumer" consumerID=1 name=spsfq subscription=chunk-subscriber topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9897748Z time="2023-03-07T10:12:37Z" level=info msg="close consumer, exit reconnect" consumerID=1 name=spsfq subscription=chunk-subscriber topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9898414Z time="2023-03-07T10:12:37Z" level=info msg="Closing producer" producerID=1 producer_name=standalone-0-422 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9899381Z time="2023-03-07T10:12:37Z" level=info msg="Closed producer" producerID=1 producer_name=standalone-0-422 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9900028Z time="2023-03-07T10:12:37Z" level=info msg="close producer, exit reconnect" producerID=1 producer_name=standalone-0-422 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9900700Z time="2023-03-07T10:12:37Z" level=info msg="Closing producer" producerID=1 producer_name=standalone-0-424 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9901256Z time="2023-03-07T10:12:37Z" level=info msg="Closed producer" producerID=1 producer_name=standalone-0-424 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9901844Z time="2023-03-07T10:12:37Z" level=info msg="close producer, exit reconnect" producerID=1 producer_name=standalone-0-424 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9902408Z time="2023-03-07T10:12:37Z" level=info msg="Closing producer" producerID=1 producer_name=standalone-0-425 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9902973Z time="2023-03-07T10:12:37Z" level=info msg="Closed producer" producerID=1 producer_name=standalone-0-425 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9903564Z time="2023-03-07T10:12:37Z" level=info msg="close producer, exit reconnect" producerID=1 producer_name=standalone-0-425 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9904129Z time="2023-03-07T10:12:37Z" level=info msg="Closing producer" producerID=1 producer_name=standalone-0-426 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9904673Z time="2023-03-07T10:12:37Z" level=info msg="Closed producer" producerID=1 producer_name=standalone-0-426 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9905262Z time="2023-03-07T10:12:37Z" level=info msg="close producer, exit reconnect" producerID=1 producer_name=standalone-0-426 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9906087Z time="2023-03-07T10:12:37Z" level=info msg="Closing producer" producerID=1 producer_name=standalone-0-427 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9906768Z time="2023-03-07T10:12:37Z" level=info msg="Closed producer" producerID=1 producer_name=standalone-0-427 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9907404Z time="2023-03-07T10:12:37Z" level=info msg="close producer, exit reconnect" producerID=1 producer_name=standalone-0-427 topic="persistent://public/default/my-topic-38610081"
2023-03-07T10:15:51.9907733Z --- FAIL: TestMaxPendingChunkMessages (1.25s)
```

### PR DESCRIPTION
**Pull request by Gleiphir2769**
Fixes #983 

### Motivation

Old TestMaxPendingChunkMessages() uses the concurrent message publish to make the consumer discard unavailable chunk. And it's flaky.

So the `sendSingeChunk()` is introduced to manual create scenarios where old chunks should be discarded.

### Modifications

- Fix `TestMaxPendingChunkMessages()`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

File: pulsar/message_chunking_test.go [hunk 1]
```diff
@@ -576,3 +548,27 @@ func createTestMessagePayload(size int) []byte {
...
+
+	producerImpl.internalSingleSend(
+		mm,
+		msg.Payload,
+		&sendRequest{
+			callback: func(id MessageID, producerMessage *ProducerMessage, err error) {},
+			msg:      msg,
+		},
+		uint32(internal.MaxMessageSize),
+	)
```
Comment (RobertIndie) [inline pulsar/message_chunking_test.go:573]: We need to flush the producer after sending the message. Or handle the callback of the `sendRequest`.

**Review by RobertIndie — CHANGES_REQUESTED** [review]

File: pulsar/message_chunking_test.go (hunk 1 above)
Comment (Gleiphir2769) [reply pulsar/message_chunking_test.go]: > We need to flush the producer after sending the message

OK, I will fix it.

**Comment by shibd** [comment]
@RobertIndie Can you retake a look?

**Review by RobertIndie — APPROVED** [review]
