### PR TITLE
Fix SIGSEGV with zstd compression enabled

### LINKED ISSUE #1163: SIGSEGV in 0.12.0 with zstd compression enabled, when producer is shared between multiple goroutines
#### Expected behavior

In release v0.11.0, sending unbatched messages with zstd compression enabled works fine.

In v0.12.0, it appears to cause a segfault.

#### Actual behavior

Segfaults of the following form are observed:

```
SIGSEGV: segmentation violation
PC=0xd41627 m=14 sigcode=1
signal arrived during cgo execution

goroutine 62 [syscall]:
runtime.cgocall(0xcf0dc0, 0xc0001ed318)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0001ed2f0 sp=0xc0001ed2b8 pc=0x409d6b
github.com/DataDog/zstd._Cfunc_ZSTD_compressCCtx(0x7f8b73d5e010, 0xc000fb3140, 0xbc, 0xc00103ad80, 0x7d, 0x9)
	_cgo_gotypes.go:223 +0x4c fp=0xc0001ed318 sp=0xc0001ed2f0 pc=0x82e48c
github.com/DataDog/zstd.(*ctx).CompressLevel.func2(0x18892e8?, 0xc0001ed3e0, 0xc0001ed3f8, 0x9)
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/!data!dog/zstd@v1.5.5/zstd_ctx.go:84 +0x127 fp=0xc0001ed388 sp=0xc0001ed318 pc=0x82f447
github.com/DataDog/zstd.(*ctx).CompressLevel(0x40fc5a?, {0xc000fb3140, 0xbc, 0xbc}, {0xc00103ad80, 0x7d, 0x7d}, 0x0?)
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/!data!dog/zstd@v1.5.5/zstd_ctx.go:84 +0xd9 fp=0xc0001ed3d8 sp=0xc0001ed388 pc=0x82f219
github.com/apache/pulsar-client-go/pulsar/internal/compression.(*zstdCGoProvider).Compress(0x0?, {0x0?, 0x413005?, 0x8?}, {0xc00103ad80?, 0x101?, 0xc0001ed4e8?})
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/apache/pulsar-client-go@v0.12.0/pulsar/internal/compression/zstd_cgo.go:64 +0x33 fp=0xc0001ed450 sp=0xc0001ed3d8 pc=0x83d1b3
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).updateChunkInfo(0xc0001a1680, 0xc000161b80)
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/apache/pulsar-client-go@v0.12.0/pulsar/producer_partition.go:1155 +0x71 fp=0xc0001ed4f8 sp=0xc0001ed450 pc=0xb64ff1
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).internalSendAsync(0xc0001a1680, {0x117c200, 0x188dc80}, 0xc0002285b0, 0xc001015930, 0x0)
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/apache/pulsar-client-go@v0.12.0/pulsar/producer_partition.go:1251 +0x517 fp=0xc0001ed718 sp=0xc0001ed4f8 pc=0xb65ad7
github.com/apache/pulsar-client-go/pulsar.(*partitionProducer).SendAsync(0xc00026cc80?, {0x117c200?, 0x188dc80?}, 0x413005?, 0xd0?)
	/builds/driftnet.io/driftnet/.go/pkg/mod/github.com/apache/pulsar-client-go@v0.12.0/pulsar/producer_partition.go:1024 +0x25 fp=0xc0001ed758 sp=0xc0001ed718 pc=0xb640a5
github.com/apache/pulsar-client-go/pulsar.(*producer).SendAsync(0xe71300?, {0x117c200, 0x188dc80}, 0x20?, 0x0?)
[...]
```

#### Steps to reproduce

I don't have test case code, but the configuration for the crashing producer is

	pulsar.ProducerOptions{
		Topic:              <topic>,
		Name:               <instanceID>,
		CompressionType:    pulsar.ZSTD,
		CompressionLevel:   pulsar.Better,
		DisableBatching:    true,
		SendTimeout:        600*time.Second,
		MaxPendingMessages: 5000,
	}

I have other producers in the system which have batching enabled and zstd compression also enabled. These are not crashing in 0.12.0.

#### System configuration

**Pulsar version**: 3.1.2
**Golang version**: 1.21.6

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #1163

Thanks @0x4500 for reporting this issue and providing the analysis. 

### Motivation

https://github.com/apache/pulsar-client-go/pull/1121 introduces a regression bug. The compression logic has been moved from `internalSend` to `internalSendAsync` which leads to the compression being executed concurrently.

However, `zstd_cgo` doesn't support concurrent compression of data. To prevent this, we need to introduce a mutex.

### Modifications

- Add mutex for zstd_cgo

### Verifying this change

I have run the benchmark and shows that this change has a minimal impact on performance.

Before this PR(I have also provided other compression provider benchmark for reference.):
```
BenchmarkCompression
BenchmarkCompression/zlib
BenchmarkCompression/zlib-12         	     388	   2904783 ns/op	  34.63 MB/s
BenchmarkCompression/lz4
BenchmarkCompression/lz4-12          	    4832	    239997 ns/op	 419.20 MB/s
BenchmarkCompression/zstd-pure-go-fastest
BenchmarkCompression/zstd-pure-go-fastest-12         	    2618	    428303 ns/op	 234.89 MB/s
BenchmarkCompression/zstd-pure-go-default
BenchmarkCompression/zstd-pure-go-default-12         	    1794	    633533 ns/op	 158.80 MB/s
BenchmarkCompression/zstd-pure-go-best
BenchmarkCompression/zstd-pure-go-best-12            	    1299	    905872 ns/op	 111.06 MB/s
BenchmarkCompression/zstd-cgo-level-fastest
BenchmarkCompression/zstd-cgo-level-fastest-12       	    7480	    176366 ns/op	 570.44 MB/s
BenchmarkCompression/zstd-cgo-level-default
BenchmarkCompression/zstd-cgo-level-default-12       	    1867	    587183 ns/op	 171.34 MB/s
BenchmarkCompression/zstd-cgo-level-best
BenchmarkCompression/zstd-cgo-level-best-12          	     620	   1855183 ns/op	  54.23 MB/s
PASS
```

After this PR:
```
BenchmarkCompression
BenchmarkCompression/zlib
BenchmarkCompression/zlib-12         	     351	   2974837 ns/op	  33.82 MB/s
BenchmarkCompression/lz4
BenchmarkCompression/lz4-12          	    4575	    223056 ns/op	 451.03 MB/s
BenchmarkCompression/zstd-pure-go-fastest
BenchmarkCompression/zstd-pure-go-fastest-12         	    2474	    412231 ns/op	 244.05 MB/s
BenchmarkCompression/zstd-pure-go-default
BenchmarkCompression/zstd-pure-go-default-12         	    1666	    641311 ns/op	 156.88 MB/s
BenchmarkCompression/zstd-pure-go-best
BenchmarkCompression/zstd-pure-go-best-12            	    1228	    882828 ns/op	 113.96 MB/s
BenchmarkCompression/zstd-cgo-level-fastest
BenchmarkCompression/zstd-cgo-level-fastest-12       	    6919	    176977 ns/op	 568.47 MB/s
BenchmarkCompression/zstd-cgo-level-default
BenchmarkCompression/zstd-cgo-level-default-12       	    1855	    586434 ns/op	 171.56 MB/s
BenchmarkCompression/zstd-cgo-level-best
BenchmarkCompression/zstd-cgo-level-best-12          	     667	   1799175 ns/op	  55.92 MB/s
PASS
```

This change added tests.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by BewareMyPower — APPROVED** [review]

**Comment by 0x4500** [comment]
Confirmed with a manual test that this PR fixes the issue in our code. Thanks @RobertIndie!

File: pulsar/internal/compression/zstd_cgo.go [hunk 1]
```diff
@@ -61,6 +64,8 @@ func (z *zstdCGoProvider) CompressMaxSize(originalSize int) int {
 }
 
 func (z *zstdCGoProvider) Compress(dst, src []byte) []byte {
+	z.mu.Lock()
+	defer z.mu.Unlock()
```
Comment (merlimat) [inline pulsar/internal/compression/zstd_cgo.go:68]: If there are many routine publishing, we could get into a contention situation. Maybe we could try some gorouting-local access? eg: https://github.com/timandy/routine?tab=readme-ov-file#use-threadlocal

Comment (0x4500) [reply pulsar/internal/compression/zstd_cgo.go:68]: Alternatively, golang provides [sync.Pool](https://pkg.go.dev/sync#Pool) which could potentially be used to create and cache zstd contexts as required.

Comment (merlimat) [reply pulsar/internal/compression/zstd_cgo.go:68]: Good point, the `sync.Pool` is already doing the thread-local caching internally.

Comment (RobertIndie) [reply pulsar/internal/compression/zstd_cgo.go:68]: Good idea! Thanks.

File: pulsar/internal/utils.go [hunk 2]
```diff
@@ -40,7 +40,7 @@ func TimestampMillis(t time.Time) uint64 {
 // GetAndAdd perform atomic read and update
 func GetAndAdd(n *uint64, diff uint64) uint64 {
 	for {
-		v := *n
+		v := atomic.LoadUint64(n)
 		if atomic.CompareAndSwapUint64(n, v, v+diff) {
```
Comment (0x4500) [inline pulsar/internal/utils.go:44]: I'm not familiar enough with the pulsar codebase to understand what this is trying to achieve, but the usual way to perform an atomic get-and-add on a uint64 in golang is to use `atomic.AddUint64()`. Also, is this change related to the issue at hand, or is it an unrelated change?

**Comment by 0x4500** [comment]
The updated version works for us -- thanks again @RobertIndie.

File: pulsar/internal/utils.go (hunk 2 above)
Comment (RobertIndie) [reply pulsar/internal/utils.go:44]: This change is to fix a race issue in the CI discovered by the new test case `TestSendConcurrently`.
The difference between them is that atomic.AddUint64() returns the new value but `GetAndAdd ` here returns the old value.
Actually I was trying to [use atomic.AddUint64()](https://github.com/apache/pulsar-client-go/pull/1164/commits/51a62c212fa1d860b162c076606484f47e69e951), but if failed in the CI because [there are other cases](https://github.com/apache/pulsar-client-go/actions/runs/7736056342/job/21092758357#step:5:9550) that need the old values.
And yes, this is to fix another regression bug introduced in 0.12.0.

**Review by 0x4500 — APPROVED** [review]

**Review by merlimat — APPROVED** [review]
