### PR TITLE
[fix] Reconnection logic and Backoff policy doesn't work correctly

### LINKED ISSUE #1187: [BUG] Reconnection logic and Backoff policy doesn't work correctly
I found that there are some issues with the BackoffPolicy:
1. We should use a new backoff instance for each use: https://github.com/apache/pulsar-client-go/blob/35ae05157b702804037446e1190a8f4e7557fdbf/pulsar/consumer_partition.go#L1656
2. In the reconnection logic, the checking for `IsMaxBackoffReached` doesn't respect the pc.options.backoffPolicy. https://github.com/apache/pulsar-client-go/blob/35ae05157b702804037446e1190a8f4e7557fdbf/pulsar/consumer_partition.go#L1700 
Actually, the `IsMaxBackoffReached` is incorrect. We should respect the operation timeout and check the whole retired time instead of the backoff delay time.
3. From the view of API design, we should move the BackoffPolicy out of the `internal` package.

### PR DESCRIPTION
**Pull request by crossoverJie**
Fixes #1187

### Modifications

- Move `backoff.go` to the `backoff` directory (because there are circular dependencies, they are not moved to the pulsar directory.)
- Create a new method for `BackOffPolicy` interface `IsMaxBackoffReached(delayReconnectTime, totalDelayReconnectTime time.Duration) bool`

This is a **breaking change** that modifies the package name and interface name.

Package: `internal`->`backoff`
Interface name: `BackoffPolicy`-> `Policy`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (yes)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (GoDocs)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by RobertIndie — COMMENTED** [review]
I'm concerned that such breaking changes could significantly impact users. Users would have to implement the new methods introduced by the backoff policy, even if they haven't encountered this issue. Perhaps we could consider including this change in the 1.0 version.

I have initiated a discussion of the Go client 1.0.0: https://lists.apache.org/thread/h022q6nrk23tz2k0qpxjf6j8m1o4qsrt

**Comment by crossoverJie** [comment]
> Perhaps we could consider including this change in the 1.0 version.

Yes, I agree with you.

File: pulsar/consumer_partition.go [hunk 1]
```diff
@@ -1673,11 +1680,8 @@ func (pc *partitionConsumer) reconnectToBroker() {
 			return
 		}
 
-		if pc.options.backoffPolicy == nil {
-			delayReconnectTime = defaultBackoff.Next()
-		} else {
-			delayReconnectTime = pc.options.backoffPolicy.Next()
-		}
+		delayReconnectTime = bo.Next()
+		totalDelayReconnectTime += delayReconnectTime
```
Comment (chinmayb) [inline pulsar/consumer_partition.go:1684]: We also need to reset the `delayReconnectTime` once connected after several retries in 1692.

**Comment by nodece** [comment]
Any updates?

File: pulsar/consumer_partition.go (hunk 1 above)
Comment (crossoverJie) [reply pulsar/consumer_partition.go:1684]: After a successful reconnection at line 1699, the function will exit, and the `delayReconnectTime` variable will be initialized during the next reconnection. 

Therefore, there is no need to reset `delayReconnectTime` here.

**Comment by crossoverJie** [comment]
The code conflicts have been resolved, but this PR involves changes to the public API. Do you recommend releasing it in version v0.13.0?

File: pulsar/backoff/backoff.go [hunk 2]
```diff
@@ -15,7 +15,7 @@
 // specific language governing permissions and limitations
 // under the License.
 
-package internal
+package backoff
```
Comment (nodece) [inline pulsar/backoff/backoff.go:18]: Could you move this pack to the `pulsar` directory and keep `BackoffPolicy`?

Comment (nodece) [inline pulsar/backoff/backoff.go:18]: Could you move this pack to the `pulsar` directory and keep `BackoffPolicy`?

File: pulsar/backoff/backoff.go [hunk 3]
```diff
@@ -26,10 +26,14 @@ func init() {
...
-// BackoffPolicy parameterize the following options in the reconnection logic to
+// Policy parameterize the following options in the reconnection logic to
 // allow users to customize the reconnection logic (minBackoff, maxBackoff and jitterPercentage)
-type BackoffPolicy interface {
+type Policy interface {
+	// Next returns the delay to wait before next retry
 	Next() time.Duration
+
+	// IsMaxBackoffReached evaluates if the max number of retries is reached
+	IsMaxBackoffReached(delayReconnectTime, totalDelayReconnectTime time.Duration) bool
```
Comment (nodece) [inline pulsar/backoff/backoff.go:36]: `delayReconnectTime` and `totalDelayReconnectTime` are unnecessary, we can record this time in the backoff. 

Usually, we need to reset this backoff when some logic works fine, could you add the `Reset()` to this interface.

File: pulsar/consumer_partition.go [hunk 4]
```diff
@@ -581,11 +583,11 @@ func (pc *partitionConsumer) getLastMessageID() (*trackingMessageID, error) {
...
 	}
 	remainTime := pc.client.operationTimeout
-	var backoff internal.BackoffPolicy
+	var bo backoff.Policy
 	if pc.options.backoffPolicy != nil {
-		backoff = pc.options.backoffPolicy
+		bo = pc.options.backoffPolicy
 	} else {
-		backoff = &internal.DefaultBackoff{}
+		bo = &backoff.DefaultBackoff{}
```
Comment (nodece) [inline pulsar/consumer_partition.go:590]:
```suggestion
		bo = NewDefaultBackoff()
```

File: pulsar/consumer_partition.go [hunk 5]
```diff
@@ -1680,18 +1682,23 @@ func (pc *partitionConsumer) internalClose(req *closeRequest) {
...
 
-	var (
-		delayReconnectTime time.Duration
-		defaultBackoff     = internal.DefaultBackoff{}
-	)
+	var bo backoff.Policy
+	if pc.options.backoffPolicy != nil {
+		bo = pc.options.backoffPolicy
+	} else {
+		bo = &backoff.DefaultBackoff{}
```
Comment (nodece) [inline pulsar/consumer_partition.go:1700]:
```suggestion
		bo = NewDefaultBackoff()
```

File: pulsar/dlq_router.go [hunk 6]
```diff
@@ -155,7 +156,7 @@ func (r *dlqRouter) getProducer(schema Schema) Producer {
 	}
 
 	// Retry to create producer indefinitely
-	backoff := &internal.DefaultBackoff{}
+	bo := &backoff.DefaultBackoff{}
```
Comment (nodece) [inline pulsar/dlq_router.go:159]: Could you pass the backoff to the `dlqRouter`?

File: pulsar/producer_partition.go [hunk 7]
```diff
@@ -448,17 +450,22 @@ func (p *partitionProducer) getOrCreateSchema(schemaInfo *SchemaInfo) (schemaVer
...
 
-	var (
-		delayReconnectTime time.Duration
-		defaultBackoff     = internal.DefaultBackoff{}
-	)
+	var bo backoff.Policy
+	if p.options.BackoffPolicy != nil {
+		bo = p.options.BackoffPolicy
+	} else {
+		bo = &backoff.DefaultBackoff{}
```
Comment (nodece) [inline pulsar/producer_partition.go:467]:
```suggestion
		bo = NewDefaultBackoff()
```

File: pulsar/backoff/backoff.go (hunk 3 above)
Comment (nodece) [reply pulsar/backoff/backoff.go:36]: If you agree with this idea, you can move the backoff object to the global scope from the local scope, which can reduce the allocation of objects.

**Review by nodece — CHANGES_REQUESTED** [review]

**Comment by nodece** [comment]
> This is a breaking change that modifies the package name and interface name.

A breaking change that we add new method to the `Backoff` interface, not change package name.

In the user project, the user cannot import the `internal` package of the pulsar library, this is a limitation, please check https://go.dev/doc/modules/layout

File: pulsar/backoff/backoff.go (hunk 2 above)
Comment (crossoverJie) [reply pulsar/backoff/backoff.go:18]: This will lead to a circular dependency.

https://github.com/apache/pulsar-client-go/blob/master/pulsar/internal/http_client.go#L151

File: pulsar/backoff/backoff.go (hunk 3 above)
Comment (crossoverJie) [reply pulsar/backoff/backoff.go]: Done.

File: pulsar/dlq_router.go (hunk 6 above)
Comment (crossoverJie) [reply pulsar/dlq_router.go:159]: Done.

**Comment by crossoverJie** [comment]
> Package: `internal`->`backoff`
> Interface name: `BackoffPolicy`-> `Policy`

Update:

`BackoffPolicy internal.BackoffPolicy` -> `BackOffPolicyFunc func() backoff.Policy`:

1. Because the Policy is concurrently called in the consumer, it has been modified to obtain a `policy` object each time using the `backoffPolicyFunc` function.

https://github.com/apache/pulsar-client-go/blob/1152cfc2e3c2024117ecff93a46d90e7eab0fa15/pulsar/consumer_partition.go#L1709-L1712


https://github.com/apache/pulsar-client-go/blob/1152cfc2e3c2024117ecff93a46d90e7eab0fa15/pulsar/consumer_partition.go#L607-L609


2. A new `Reset` function has been added to the Policy interface, which will be called after a successful reconnection. If a user's custom Policy requires the reuse of the same object, the data can be reset within this `Reset` function.

File: pulsar/producer_partition.go [hunk 8]
```diff
@@ -473,11 +485,10 @@ func (p *partitionProducer) reconnectToBroker(connectionClosed *connectionClosed
 			delayReconnectTime = 0
 			assignedBrokerURL = connectionClosed.assignedBrokerURL
 			connectionClosed = nil // Only attempt once
-		} else if p.options.BackoffPolicy == nil {
-			delayReconnectTime = defaultBackoff.Next()
 		} else {
-			delayReconnectTime = p.options.BackoffPolicy.Next()
+			delayReconnectTime = bo.Next()
 		}
+		totalDelayReconnectTime += delayReconnectTime
```
Comment (nodece) [inline pulsar/producer_partition.go:491]:
```suggestion
```

File: pulsar/producer_partition.go [hunk 9]
```diff
@@ -448,17 +460,17 @@ func (p *partitionProducer) getOrCreateSchema(schemaInfo *SchemaInfo) (schemaVer
 }
 
 func (p *partitionProducer) reconnectToBroker(connectionClosed *connectionClosed) {
-	var maxRetry int
+	var (
+		maxRetry                                    int
+		delayReconnectTime, totalDelayReconnectTime time.Duration
```
Comment (nodece) [inline pulsar/producer_partition.go:465]:
```suggestion
```

File: pulsar/producer_test.go [hunk 10]
```diff
@@ -1273,11 +1275,13 @@ func TestProducerWithBackoffPolicy(t *testing.T) {
...
-	backoff := newTestBackoffPolicy(1*time.Second, 4*time.Second)
+	bo := newTestBackoffPolicy(1*time.Second, 4*time.Second)
 	_producer, err := client.CreateProducer(ProducerOptions{
-		Topic:         topicName,
-		SendTimeout:   2 * time.Second,
-		BackoffPolicy: backoff,
+		Topic:       topicName,
+		SendTimeout: 2 * time.Second,
+		BackOffPolicyFunc: func() backoff.Policy {
+			return bo
```
Comment (nodece) [inline pulsar/producer_test.go:1283]:
```suggestion
			return newTestBackoffPolicy(1*time.Second, 4*time.Second)
```

File: pulsar/dlq_router.go (hunk 6 above)
Comment (nodece) [reply pulsar/dlq_router.go:159]: DefaultBackoff will still be used?

**Review by nodece — APPROVED** [review]

File: pulsar/backoff/backoff.go [hunk 11]
```diff
@@ -38,6 +45,13 @@ type DefaultBackoff struct {
 	backoff time.Duration
 }
 
+func NewDefaultBackoff() Policy {
+	return &DefaultBackoff{}
+}
+func NewDefaultBackoffWithBackOff(backoff time.Duration) Policy {
```
Comment (RobertIndie) [inline pulsar/backoff/backoff.go:51]:
```suggestion
func NewDefaultBackoffWithInitialBackOff(backoff time.Duration) Policy {
```

Seems this name would be better?

File: pulsar/backoff/backoff.go [hunk 12]
```diff
@@ -38,6 +45,13 @@ type DefaultBackoff struct {
...
+	return &DefaultBackoff{backoff: backoff}
```
Comment (RobertIndie) [inline pulsar/backoff/backoff.go:52]:
```suggestion
	return &DefaultBackoff{backoff: backoff / 2}
```

I think we should treat this as the initial backoff time, right? 
If it's, then we need to first divide the backoff by 2. Because each time Next is called, the backoff is doubled first.

**Review by RobertIndie — COMMENTED** [review]
Please help resolve the conflicts

**Review by RobertIndie — APPROVED** [review]
