### PR TITLE
[Issue 1384][consumer] Fix the default nack backoff policy

### LINKED ISSUE #1384: [Bug] default nack backoff policy overflows to zero
#### Expected behavior

The default nack backoff policy should return the maximum backoff time once reaching an arbitrary high redelivery count.

#### Actual behavior

The default nack backoff policy returns zero once a sufficiently big redelivery count is reached.

#### Steps to reproduce

```Go
func TestDefaultNackBackoffPolicy_Next(t *testing.T) {
	defaultNackBackoff := new(defaultNackBackoffPolicy)

	res := defaultNackBackoff.Next(math.MaxUint32)
	assert.Equal(t, 10*time.Minute, res)
}
```

#### System configuration
**Pulsar version**: v4.0.5
**Pulsar Go client**: v0.15.1

### PR DESCRIPTION
**Pull request by Gilthoniel**
Fixes #1384 

### Motivation

Once the redelivery count is high enough, the backoff time overflows to zero causing immediate redelivery.

### Modifications

Check for the overflow to assign the max backoff time in that case.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as:
- Extend `TestDefaultNackBackoffPolicy_Next` with failing cases added.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

File: pulsar/negative_backoff_policy.go [hunk 1]
```diff
@@ -41,9 +41,11 @@ func (nbp *defaultNackBackoffPolicy) Next(redeliveryCount uint32) time.Duration
 	minNackTime := 1 * time.Second  // 1sec
 	maxNackTime := 10 * time.Minute // 10min
 
-	if redeliveryCount < 0 {
```
Comment (Gilthoniel) [inline pulsar/negative_backoff_policy.go:44]: Please note that it cannot be below zero as the type is `uint32`.

**Comment by Gilthoniel** [comment]
Rebase done to fix the previous issue on master.

**Review by crossoverJie — APPROVED** [review]
LGTM
