### PR TITLE
[fix] [issue 1057]:  Fix the producer flush opertion is not guarantee to flush all messages

### LINKED ISSUE #1057: [BUG] The producer flush opertion is not guarantee to flush all messages
#### Expected behavior

The `producer.Flush` should guarantee that all the messages should be flushed to the broker.

#### Actual behavior

The flush operation may skip some messages in the producer.

#### Steps to reproduce

```go
producer.SendAsync(context.Background(), &ProducerMessage{
		Payload: []byte("hello"),
	}, nil)
err = producer.Flush()
if err != nil {
	return
}
```
Currently, the Flush cannot guarantee that the message `hello` is actually flushed to the broker.

The root cause is that when calling the SendAsync, the producer will create another go routine to put the message to the queue.
Therefore, when flush is called, the message may not have entered the queue yet.

#### System configuration
**Pulsar Go version**: master

### PR DESCRIPTION
**Pull request by Gleiphir2769**
Fixes #1057 

### Motivation

`dataChan` is introduced by #1029  to fix the problem of reconnectToBroker. But it missed that if a flush operation excuted, there may still be some messages in `dataChan`. And these messages can't be flushed.

### Modifications

- Fix the producer flush opertion is not guarantee to flush all messages

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

File: pulsar/producer_partition.go [hunk 1]
```diff
@@ -1041,6 +1041,12 @@ func (p *partitionProducer) internalFlushCurrentBatches() {
 }
 
 func (p *partitionProducer) internalFlush(fr *flushRequest) {
+	oldDataChan := p.dataChan
+	p.dataChan = make(chan *sendRequest, p.options.MaxPendingMessages)
+	for len(oldDataChan) != 0 {
+		pendingData := <-oldDataChan
+		p.internalSend(pendingData)
+	}
```
Comment (RobertIndie) [inline pulsar/producer_partition.go:1049]:
```suggestion
	if len(p.dataChan) != 0 {
		oldDataChan := p.dataChan
		p.dataChan = make(chan *sendRequest, p.options.MaxPendingMessages)
		for len(oldDataChan) != 0 {
			pendingData := <-oldDataChan
			p.internalSend(pendingData)
		}
	}
```

Comment (Gleiphir2769) [reply pulsar/producer_partition.go:1049]: You r right. We should check length of dataChan first.

**Review by RobertIndie — APPROVED** [review]
