### PR TITLE
[Issue 1276] Fix multiple consumers using zeroQueueConsumer

### LINKED ISSUE #1276: EnableZeroQueueConsumer Setting Not Functioning Correctly
Description
I've encountered an issue with the Pulsar client where setting EnableZeroQueueConsumer: true does not produce the expected behavior. The client continues to perform extra reads into the buffer, which contradicts the purpose of this setting.
Steps to Reproduce

Configure the Pulsar client with EnableZeroQueueConsumer: true
Observe the client's behavior during message consumption

Expected Behavior
When EnableZeroQueueConsumer is set to true, the client should not perform extra reads into the buffer. It should only fetch messages as they are consumed.
Actual Behavior
The client continues to read additional messages into the buffer, despite the EnableZeroQueueConsumer setting being enabled.
Additional Information
I've reviewed the code and I'm confident there's an issue in the implementation of this feature. The extra buffering occurs consistently, regardless of the EnableZeroQueueConsumer setting.
Environment

Pulsar Client Version: v0.13.1  
Server : [apachepulsar/pulsar:3.3.1] (docker)

Any assistance in investigating and resolving this issue would be greatly appreciated. Thank you for your time and attention to this matter.

image

### PR DESCRIPTION
**Pull request by crossoverJie**
Fixes #1276

Master Issue: #<xyz>

### Motivation
In the current situation, when using `zeroQueueConsumer`, the permits will be incremented an additional time.

### Modifications

When using `zeroQueueConsumer`, the permits are managed by itself.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable / docs / GoDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: pulsar/consumer_zero_queue_test.go [hunk 1]
```diff
@@ -95,6 +95,89 @@ func TestNormalZeroQueueConsumer(t *testing.T) {
...
+	})
+	assert.Nil(t, err)
+	_, ok = consumer2.(*zeroQueueConsumer)
+	assert.True(t, ok)
+	defer consumer2.Close()
+
+	// create producer
+	producer, err := client.CreateProducer(ProducerOptions{
+		Topic:           topic,
+		DisableBatching: false,
```
Comment (nodece) [inline pulsar/consumer_zero_queue_test.go:138]:
```suggestion
		DisableBatching: true,
```

Is it right?

**Review by nodece — APPROVED** [review]
