### PR TITLE
[Issue 556]Add jitter to exponential backoff (#556)

### LINKED ISSUE #556: Backoff is calculated without jitter
The problem occurs when the connection to the broker is lost. The client will try to reconnect with an exponential backoff. The problem is that there is no jitter involved when calculating the backoff delay.

#### Expected behavior

Not all clients try to reconnect at the same time. 

#### Actual behavior

All clients try to reconnect at the same time to the brokers

#### Steps to reproduce

- Set up multiple clients connecting to the same set of brokers.
- Break the connection between the clients and the brokers

#### System configuration
**Pulsar version**: 0.5.0

### PR DESCRIPTION
**Pull request by dvergnes**
Fixes #556 

### Motivation
When reconnecting to a broker, an exponential backoff strategy is used. However, there is no randomness involved which means in case of a general outage impacting several clients, they will try to reconnect at the same time.

### Modifications

The modification consists of adding a jitter that adds 20% of delay after the delay is doubled on each retry.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added unit tests to verify the expected behavior.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no)
  - The wire protocol: no

### Documentation

  - Does this pull request introduce a new feature? no
  - If yes, how is the feature documented? not applicable
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: pulsar/internal/backoff.go [hunk 1]
```diff
@@ -40,6 +43,7 @@ func (b *Backoff) Next() time.Duration {
 	} else if b.backoff.Nanoseconds() > maxBackoff.Nanoseconds() {
 		b.backoff = maxBackoff
 	}
+	jitter := rand.Float64() * float64(b.backoff) * jitterPercentage
```
Comment (cckellogg) [inline pulsar/internal/backoff.go:46]: Does the generator need to be seeded (https://golang.org/pkg/math/rand/#Seed)?

Comment (dvergnes) [reply pulsar/internal/backoff.go:50]: Yes, you are right. I updated the PR.

**Review by cckellogg — APPROVED** [review]

**Review by freeznet — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]
