### PR TITLE
[issue:40]Fix producer send protocol error

### LINKED ISSUE #40: When using the go client's producer to send messages, the cgo client's consumer cannot be consumed normally.
#### Expected behavior

When using the go client's producer to send messages, the cgo client's consumer can be consumed normally.

#### Actual behavior

go client producer:

```
func main() {
    client, err := pulsar.NewClient(pulsar.ClientOptions{
        URL: "pulsar://localhost:6650",
    })

    if err != nil {
        log.Fatal(err)
    }

    defer client.Close()

    producer, err := client.CreateProducer(pulsar.ProducerOptions{
        Topic: "my-topic-1",
    })
    if err != nil {
        log.Fatal(err)
    }

    defer producer.Close()

    ctx := context.Background()

    for i := 0; i < 10; i++ {
        if err := producer.Send(ctx, &pulsar.ProducerMessage{
            Payload: []byte(fmt.Sprintf("hello-%d", i)),
        }); err != nil {
            log.Fatal(err)
        }
    }
}
```

cgo client consumer:

```
func main() {
	client, err := pulsar.NewClient(pulsar.ClientOptions{URL: "pulsar://localhost:6650"})
	if err != nil {
		log.Fatal(err)
	}

	defer client.Close()

	consumer, err := client.Subscribe(pulsar.ConsumerOptions{
		Topic:            "my-topic-1",
		SubscriptionName: "my-subscription",
		Type:             pulsar.Shared,
	})
	if err != nil {
		log.Fatal(err)
	}

	defer consumer.Close()

	for {
		msg, err := consumer.Receive(context.Background())
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("Received message  msgId: %s -- content: '%s'\n",
			msg.ID(), string(msg.Payload()))

		consumer.Ack(msg)
	}
}
```

cgo client receive payload content is nil.

```
Received message  msgId: (4,0,-1,0) -- content: ''
Received message  msgId: (4,1,-1,0) -- content: ''
Received message  msgId: (4,2,-1,0) -- content: ''
Received message  msgId: (4,3,-1,0) -- content: ''
Received message  msgId: (4,4,-1,0) -- content: ''
Received message  msgId: (4,5,-1,0) -- content: ''
Received message  msgId: (4,6,-1,0) -- content: ''
Received message  msgId: (4,7,-1,0) -- content: ''
Received message  msgId: (4,8,-1,0) -- content: ''
Received message  msgId: (4,9,-1,0) -- content: ''
```
#### Steps to reproduce

How can we reproduce the issue

#### System configuration
**Pulsar version**: x.y

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

Fixes #40 #39 #33 

### Motivation

"Payload" command frame format (It has the same 3 fields as a "simple" command, plus the following):

|"Simple" fields var length|magicNumber (0x0e01) 2 bytes|checksum (CRC32-C) 4 bytes| metadataSize (uint32) 4 bytes| metadata (protobuf encoded) var length| payload (bytes) totalSize - (SUM others)|
|----|----|----|----|----|----|
||OPTIONAL If present, indicates following 4 bytes are checksum|OPTIONAL Checksum of the following bytes| size of the metadata| |Any sequence of bytes, possibly compressed and or encrypted (see metadata)|

When using batch messages, the payload will be containing a list of entries, each of them with its individual metadata, defined by the `SingleMessageMetadata` object.

```
singleMetaSize(4  bytes) + singleMeta(var length) + payload
```

Go client producer send code as follows：

```
producer.Send(ctx, &pulsar.ProducerMessage{
            Payload: []byte(fmt.Sprintf("hello-%d", i)),
            Key:     "pulsar",
            Properties: map[string]string{
                "key":"apache",
            },
```

output byte slice as follows:

```
0a 0d 0a 03
     6b 65 79 message properties key: key（3 bytes）
12 06
    61 70 61 63 68 65 properties value: apache（6 bytes）
12 06
    70 75 6c 73 61 72 message key: pulsar（6 bytes）
18 07
    68 65 6c 6c 6f 2d 39 message payload: hello-%d（7 bytes）
```

We can see that in the output byte slice, we did not find the singleMetaSize(4 bytes) field in `SingleMessageMetadata`.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jiazhai @merlimat PTAL

File: pulsar/internal/commands_test.go [hunk 1]
```diff
@@ -37,3 +37,19 @@ func TestConvertStringMap(t *testing.T) {
 	assert.Equal(t, "1", m2["a"])
 	assert.Equal(t, "2", m2["b"])
 }
+
+func TestDecodeBatchPayload(t *testing.T) {
+	payload := []byte{0, 0, 0, 2, 24, 12, 104, 101, 108, 108, 111, 45, 112, 117, 108, 115, 97, 114} // hello-pulsar
```
Comment (jiazhai) [inline pulsar/internal/commands_test.go]: Seems this is batch payload, contains a single message of payload "hello-pulsar"

File: pulsar/internal/commands.go [hunk 2]
```diff
@@ -163,24 +164,26 @@ func ParseMessage(headersAndPayload []byte) (msgMeta *pb.MessageMetadata, payloa
...
-		if lr.N > MaxFrameSize {
-			return nil, nil, fmt.Errorf("frame payload size (%d) "+
-					"cannot be greater than max frame size (%d)", lr.N, MaxFrameSize)
-		}
-		payload = make([]byte, lr.N)
-		if _, err = io.ReadFull(lr, payload); err != nil {
-			return nil, nil, err
-		}
-	}
+    numMsg := msgMeta.GetNumMessagesInBatch()
```
Comment (sijie) [inline pulsar/internal/commands.go]: the indent from line 167 to line 186 seems to be not aligned with line 188 and forward. is that an issue?

Comment (wolfstudy) [reply pulsar/internal/commands.go]: Yes, will run `gofmt` to check code format.

**Comment by wolfstudy** [comment]
@sijie PTAL again, thanks.
